# GET http://localhost:8000/api/v1/health

# GET http://localhost:8000/api/v1/health/db

# GET http://localhost:8000/api/v1/not-exist

### Register
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "username": "Test User2",
  "email": "test2@gmail.com",
  "password": "123456"
}

### Login
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "test@gmail.com",
  "password": "123456"
}

### Me
GET http://localhost:8000/api/v1/auth/me
Authorization: Bearer <token>




### Get topics
GET http://localhost:8000/api/v1/topics
Authorization: Bearer <access_token>

### Create topic
POST http://localhost:8000/api/v1/topics
Authorization: Bearer <access_token>
Content-Type: application/json

{
  "name": "Machine Learning"
}

### Update topic
PUT http://localhost:8000/api/v1/topics/1
Authorization: Bearer <access_token>
Content-Type: application/json

{
  "name": "Deep Learning"
}

### Delete topic
DELETE http://localhost:8000/api/v1/topics/1
Authorization: Bearer <access_token>
