"""them_topic_id_vao_bang_paper

Revision ID: d39714405368
Revises: b013cd206c13
Create Date: 2026-05-13 01:02:52.694755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd39714405368'
down_revision: Union[str, Sequence[str], None] = 'b013cd206c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('topic_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'papers', 'topics', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'papers', type_='foreignkey')
    op.drop_column('papers', 'topic_id')
    # ### end Alembic commands ###
