"""add_avg_rating_column_to_papers

Revision ID: e192a41f90eb
Revises: b813dd37eebb
Create Date: 2026-05-18 22:58:39.880898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e192a41f90eb'
down_revision: Union[str, Sequence[str], None] = 'b813dd37eebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('avg_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'avg_rating')
    # ### end Alembic commands ###
